homework_08/furnitureshop/furniture/urls.py
from django.urls import path
from django.contrib import admin

import furniture.views as furnitures


app_name = 'furniture'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', furnitures.index, name='index'),
    path('furniture/',
         furnitures.FurnitureListView.as_view(),
         name='list'),
    path('furniture/supplier_detail/<int:pk>/',
         furnitures.FurnitureSupplierDetailView.as_view(template_name="furniture/supplier_detail.html"),
         name='supplier'),
    path('furniture/update/<int:item_pk>/',
         furnitures.FurnitureUpdateView.as_view(template_name="furniture/furniture_update.html"),
         name='furniture_update'),
    path('furniture/material_detail/<int:pk>/',
         furnitures.FurnitureMaterialDetailView.as_view(template_name="furniture/material_detail.html"),
         name='furniture_material'),
]

homework_08/furnitureshop/furniture/models.py
from django.db import models


class FurnitureSupplier(models.Model):
    name = models.CharField(max_length=32, null=False, unique=True)
    email = models.CharField(max_length=32, null=False)
    address = models.CharField(max_length=64, null=False)
    phone_number = models.IntegerField(null=False)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return f'{self.name}    {self.email}'


class Furniture(models.Model):
    type = models.CharField(max_length=128)
    supplier = models.ForeignKey(FurnitureSupplier,
                                 on_delete=models.CASCADE,
                                 null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_new = models.BooleanField(default=False)

    class Meta:
        ordering = ['updated_at']

    def my_furniture(self):
        furniture = self.furniturematerial_set.all()
        return ', '.join(map(str, furniture))

    def __str__(self):
        return self.type


class FurnitureDetail(models.Model):
    furniture = models.OneToOneField('furniture.Furniture',
                                     primary_key=True,
                                     on_delete=models.CASCADE)
    discription = models.TextField()

    def __str__(self):
        return self.furniture


class FurnitureMaterial(models.Model):
    material = models.CharField(max_length=64, unique=True)
    furniture = models.ManyToManyField(Furniture)

    def __str__(self):
        return self.material


class Store(models.Model):
    name = models.CharField(max_length=300)
    books = models.ManyToManyField(Furniture)

    class Meta:
        default_related_name = 'stores'

    def __str__(self):
        return self.name

homework_08/furnitureshop/furniture/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DetailView
from furniture.models import Furniture, FurnitureSupplier, FurnitureMaterial

from django.shortcuts import render


def index(request):
    return render(request, 'base.html')


class FurnitureListView(ListView):
    model = Furniture
    ordering = ['-updated_at']


class FurnitureSupplierDetailView(DetailView):
    model = FurnitureSupplier


class FurnitureMaterialDetailView(DetailView):
    model = FurnitureMaterial


class FurnitureUpdateView(UpdateView):
    model = Furniture
    success_url = reverse_lazy('furniture:list')
    fields = ('type',)
    pk_url_kwarg = 'item_pk'

homework_08/furnitureshop/furniture/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>
        {% block title %}
        Base title
        {% endblock %}
    </title>
  </head>
  <body>
    <div class="container">

      <nav>
          <a href="/" style="font-size:24px;">
              Main
          </a>
          <a href="{% url 'furniture:list' %}" style="font-size:24px; margin-left: 40px;">
              Furniture list
          </a>
      </nav>
        {% block body %}
        {% endblock %}
    </div>
  </body>
</html>

homework_08/furnitureshop/furniture/templates/furniture/furniture_list.html
{% extends 'base.html' %}

{% block title %}
Furniture list
{% endblock %}

{% block body %}
    <div class="furniture-list">
        <ul>
            {% for item in furniture_list %}
                <li>
                    {{ item }}

                    <a href="{% url 'furniture:furniture_material' item.id%}" style="margin-left: 40px;">
                        Материал
                    </a>
                    <a href="{% url 'furniture:supplier' item.id%}" style="margin-left: 40px;">
                        Поставщик
                    </a>
                    <a href="{% url 'furniture:furniture_update' item.id %}" style="margin-left: 40px;">
                        Update
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

homework_08/furnitureshop/furniture/templates/furniture/material_detail.html
{% extends 'base.html' %}

{% block title %}
Material detail
{% endblock %}

{% block body %}
    <h3>Информация по материалу</h3>
    <div class="detail-list">
        <ul>
                <li>
                  {{ furniturematerial.material }}
                </li>
        </ul>
        <a href="{% url 'furniture:list' %}">
          Back to furniture list
        </a>
    </div>
{% endblock %}

homework_08/furnitureshop/furniture/templates/furniture/supplier_detail.html
{% extends 'base.html' %}

{% block title %}
Detail
{% endblock %}
{% block body %}
    <h2>Информация по поставщику</h2>
    <div class="detail-list">
        <ul>
                <li>
                  {{ furnituresupplier.name }}
                </li>
                <li>
                    {{ furnituresupplier.email }}
                </li>
                <li>
                    {{ furnituresupplier.address }}
                </li>
        </ul>
        <a href="{% url 'furniture:list' %}" style="font-size:24px;">
          Back to furniture list
        </a>
    </div>
{% endblock %}