Final project/furnitureshop/cart/urls.py
from django.urls import path
import cart.views as view


app_name = 'cart'

urlpatterns = [
    path('cart_detail/', view.cart_detail, name='detail'),
    path('add/<int:id>/', view.cart_add, name='cart_add'),
    path('remove/<int:id>/', view.cart_remove, name='cart_remove'),
]

Final project/furnitureshop/furniture/urls.py
from django.urls import path
from django.contrib import admin

import furniture.views as furnitures


app_name = 'furniture'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', furnitures.furniture_list,
         name='furniture_list'),
    path('<slug:category_slug>/',
         furnitures.furniture_list,
         name='furniture_list_category'),
    path('<int:id>/<slug:slug>',
         furnitures.furniture_detail,
         name='furniture_detail')
]

Final project/furnitureshop/furnitureshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from furnitureshop.settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('sauth.urls', namespace='user')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('furniture.urls', namespace='furniture')),
]

if DEBUG:
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Final project/furnitureshop/sauth/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
import sauth.views as auth

app_name = 'user'

urlpatterns = [
    path('user/create/',
         auth.ShopUserCreateView.as_view(),
         name='user_create'),
    path('login/',
         LoginView.as_view(),
         name='login'),
    path('logout/',
         LogoutView.as_view(),
         name='logout'),
]

Final project/furnitureshop/furniture/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=120, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def _str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('furniture:furniture_list_category', args=[self.slug])


class Furniture(models.Model):
    category = models.ForeignKey('Category',
                                 related_name='products',
                                 on_delete=models.CASCADE,)
    name = models.CharField(max_length=64, db_index=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    slug = models.SlugField(max_length=200, db_index=True)
    description = models.TextField(blank=True)
    available = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('furniture:furniture_detail', args=[self.id, self.slug])

Final project/furnitureshop/furniture/views.py
from django.core.paginator import Paginator
from cart.forms import CartAddProductForm
from furniture.models import Furniture, Category
from django.shortcuts import render, get_object_or_404


def index(request):
    return render(request, 'furniture/index.html')


def furniture_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    furnitures = Furniture.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        furnitures = furnitures.filter(category=category)
    context = {
        'category': category,
        'categories': categories,
        'furnitures': furnitures,
    }
    return render(request,
                  'furniture/furniture_list.html',
                  context=context)


def furniture_detail(request, id, slug):
    funriture = get_object_or_404(Furniture,
                                  id=id,
                                  slug=slug,
                                  available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'furniture': funriture,
        'cart_product_form': cart_product_form
    }
    return render(request,
                  'furniture/furniture_detail.html',
                  context=context)

Final project/furnitureshop/furniture/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>{% block title %}Мой магазин{% endblock %}</title>
<link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
<body>
<div id="header">
<a href="/" class="logo">Фактура-мебель</a>
</div>
<div id="subheader">
     {% if user.is_authenticated %}
            <a href="{% url 'user:logout' %}">
                Logout ({{ user.username }})
            </a>
        {% else %}
            <a href="{% url 'user:login' %}">
                Вход
            </a>
    {% endif %}
    <div class="cart">
        {% with total_items=cart|length %}
            {% if cart|length > 0 %}
                В корзине
                <a href="{% url 'cart:detail' %}">
                    {% if cart|length == 1 %}
                        {{ total_items }} товар{{ total_items|pluralize }},
                        Р{{ cart.get_total_price }}
                    {% elif cart|length <= 4 %}
                        {{ total_items }} товара {{ total_items|pluralize }},
                        Р{{ cart.get_total_price }}
                    {% elif cart|length > 4  %}
                        {{ total_items }} товаров{{ total_items|pluralize }},
                        Р{{ cart.get_total_price }}
                    {% endif %}
                </a>
            {% else %}
                Корзина пуста
            {% endif %}
        {% endwith %}
    </div>
</div>
<div id="content">
{% block content %}
{% endblock %}
</div>
</body>
</html>