Final project/furnitureshop/cart/urls.py
from django.urls import path
import cart.views as view


app_name = 'cart'

urlpatterns = [
    path('cart_detail/', view.cart_detail, name='detail'),
    path('add/<int:id>/', view.cart_add, name='cart_add'),
    path('remove/<int:id>/', view.cart_remove, name='cart_remove'),
]

Final project/furnitureshop/furniture/urls.py
from django.urls import path
from django.contrib import admin

import furniture.views as furnitures


app_name = 'furniture'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', furnitures.furniture_list,
         name='furniture_list'),
    path('<slug:category_slug>/',
         furnitures.furniture_list,
         name='furniture_list_category'),
    path('<int:id>/<slug:slug>',
         furnitures.furniture_detail,
         name='furniture_detail')
]

Final project/furnitureshop/furnitureshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from furnitureshop.settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('sauth.urls', namespace='user')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('furniture.urls', namespace='furniture')),
]

if DEBUG:
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Final project/furnitureshop/furniture/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=120, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def _str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('furniture:furniture_list_category', args=[self.slug])


class Furniture(models.Model):
    category = models.ForeignKey('Category',
                                 related_name='products',
                                 on_delete=models.CASCADE,)
    name = models.CharField(max_length=64, db_index=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    slug = models.SlugField(max_length=200, db_index=True)
    description = models.TextField(blank=True)
    available = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('furniture:furniture_detail', args=[self.id, self.slug])

Final project/furnitureshop/furniture/views.py
from django.core.paginator import Paginator
from cart.forms import CartAddProductForm
from furniture.models import Furniture, Category
from django.shortcuts import render, get_object_or_404


def index(request):
    return render(request, 'furniture/index.html')


def furniture_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    furnitures = Furniture.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        furnitures = furnitures.filter(category=category)
    context = {
        'category': category,
        'categories': categories,
        'furnitures': furnitures,
    }
    return render(request,
                  'furniture/furniture_list.html',
                  context=context)


def furniture_detail(request, id, slug):
    funriture = get_object_or_404(Furniture,
                                  id=id,
                                  slug=slug,
                                  available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'furniture': funriture,
        'cart_product_form': cart_product_form
    }
    return render(request,
                  'furniture/furniture_detail.html',
                  context=context)

Final project/furnitureshop/furniture/templates/furniture/furniture_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Furniture detail
{% endblock %}

{% block content %}
    <div class="product-detail">
    <img src="{% if furniture.image %}{{ furniture.image.url }}{%else %}{% static 'img/no_image.png' %}{% endif %}" width="250" height="450">
    <h1>{{ furniture.name }}</h1>
    <h2>
    <a href="{{ furniture.category.get_absolute_url }}">{{furniture.category.name }}</a>
    </h2>
    <p class="price">Р{{ furniture.price }}</p>
    {{ furniture.description|linebreaks }}
    </div>
    <form action="{% url 'cart:cart_add' furniture.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Добавить в корзину">
    </form>
{% endblock %}

Final project/furnitureshop/furniture/templates/furniture/furniture_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Все товары{% endif %}
{% endblock %}
{% block content %}
    <div id="sidebar">
        <h3>Категории товара</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
            <a href="{% url 'furniture:furniture_list' %}">Все</a>
            </li>
            {% for c in categories %}
            <li {% if category.slug == c.slug %}class="selected" {% endif %}>
            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main1" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Все товары{% endif %}</h1>
        {% for furniture in furnitures %}
            <div class="item">
                <a href="{{ furniture.get_absolute_url }}">
                    <img src="{% if furniture.image %}{{ furniture.image.url }}{%else %}{% static 'img/no_image.png' %}{% endif %}" width="250" height="300">
                </a>
                <br>
                <a href="{{ furniture.get_absolute_url }}">{{ furniture.name }}</a>
                <br>
                {{ furniture.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %}

Final project/furnitureshop/furniture/templates/furniture/furniture_update.html
{% extends 'base.html' %}

{% block title %}
Furniture update
{% endblock %}

{% block body %}

    <form method="post" style="margin-top: 20px;">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="save">
    </form>
{% endblock %}