Final project/furnitureshop/cart/urls.py
from django.urls import path
import cart.views as view


app_name = 'cart'

urlpatterns = [
    path('cart_detail/', view.cart_detail, name='detail'),
    path('add/<int:id>/', view.cart_add, name='cart_add'),
    path('remove/<int:id>/', view.cart_remove, name='cart_remove'),
]

Final project/furnitureshop/furniture/urls.py
from django.urls import path
from django.contrib import admin

import furniture.views as furnitures


app_name = 'furniture'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', furnitures.furniture_list,
         name='furniture_list'),
    path('<slug:category_slug>/',
         furnitures.furniture_list,
         name='furniture_list_category'),
    path('<int:id>/<slug:slug>',
         furnitures.furniture_detail,
         name='furniture_detail')
]

Final project/furnitureshop/furnitureshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from furnitureshop.settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('sauth.urls', namespace='user')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('furniture.urls', namespace='furniture')),
]

if DEBUG:
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Final project/furnitureshop/orders/urls.py
from django.urls import path
from django.contrib import admin

import orders.views as order


app_name = 'order'

urlpatterns = [
    path('create/', order.order_create,
         name='order_create'),
]

Final project/furnitureshop/cart/models.py
from django.db import models

# Create your models here.

Final project/furnitureshop/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

Final project/furnitureshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from furniture.models import Furniture
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, id):
    cart = Cart(request)
    product = get_object_or_404(Furniture,
                                id=id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update=cd['update'])
    return redirect('cart:detail')


def cart_remove(request, id):
    cart = Cart(request)
    product = get_object_or_404(Furniture, id=id)
    cart.remove(product)
    return redirect('cart:detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    context = {
        'cart': cart
    }

    return render(request, 'cart/detail.html', context)

Final project/furnitureshop/cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Корзина
{% endblock %}
{% block content %}
    <h1>Корзина</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Фото</th>
            <th>Твар</th>
            <th>Кол-во</th>
            <th>Удалить</th>
            <th>Общая</th>
            <th>Цена 1 ед.</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static 'img/no_image.png' %}
                                {% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url 'cart:cart_remove' product.id%}">Удалить</a></td>
                    <td class="num">{{ item.price }}</td>
                    <td class="num">{{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">Р{{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'furniture:furniture_list' %}" class="button light">К списку товаров</a>
        <a href="{% url 'order:order_create' %}" class="button">
        Оформить заказ
        </a>
    </p>
{% endblock %}